### ISSUE TITLE
NGR ERROR SyntaxError: Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by gkontokotsios** [steveblue/angular2-rollup#26] opened 2018-11-21 13:57 UTC
Hello.

I installed the latest version of angular-rollup and I created a new project using:
`$ ngr new my-app`

I immediately tried building this project but I get this error:

`$ ngr build prod`
rollup completed 
NGR ERROR SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at ReadFileContext.fs.readFile [as callback] (/usr/local/lib/node_modules/angular-rollup/src/build/prod.js:160:29)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:235:13)

`$ ngr -V`
2.0.1

`$ npm --version`
6.4.1

`$ node --version`
v10.12.0

Thanks!

**Comment by steveblue** [comment] 2018-11-22 03:41
This is erroring on the part of the build that bundles rxjs. Out of curiosity, which version of rxjs are you running currently and what is your environment @gkontokotsios Mac, Windows? Do you have rxjs properly installed in the node_modules directory?

**Comment by gkontokotsios** [comment] 2018-11-22 09:47
Hi @steveblue. I am working on a Mac (Mojave v10.14.1).
This issue can be reproduced without changing anything on a freshly generated project.
`$ ngr new my-app` creates a project with a dependency to:
`"rxjs": "~6.3.3"`

Also it takes care of running `npm install` and indeed rxjs is correctly installed in the node_modules directory.

And running `ngr build prod` always fails with the above issue.

**Comment by steveblue** [comment] 2018-11-23 06:12
I am not able to reproduce even with same configuration (node 10.12.0, angular-rollup 2.0.1). The issue indicates the package.json is being returned as `undefined`, as `Unexpected token u in JSON at position 0` is typically the error returned when the object passed into `JSON.parse()` is `undefined`. 

Since I am not able to reproduce, the steps you would need to diagnose further:

Clone this repo.
Run `npm install`
Run `npm link`

This last command will link the repo to the global scope as if you ran `npm i -g angular-rollup`.

Find line 160 in prod.js and see what filePath and stdout return. Using console.log here will print to Terminal.

**Comment by gkontokotsios** [comment] 2018-11-24 11:13
Hi @steveblue, thank for your support. I did exactly what you proposed and I get the following:
**filePath:** node_modules/rxjs/websocket/package.json
**stdout:** undefined

**Comment by gkontokotsios** [comment] 2018-11-24 13:34
@steveblue: I that the error is caused because in prod.js, line 188 the path to webSocket is with a lowercase **s**:
`node_modules/rxjs/webSocket/package.json`

After changing this, the build worked on my system without further errors

**Comment by steveblue** [comment] 2018-11-27 05:41
Merged into develop.

**Closed by steveblue** 2018-11-27 05:41 UTC
Labels: bug, triage

**Comment by steveblue** [comment] 2018-11-27 05:50
TY @gkontokotsios for looking into it. Let me know how you are getting along with Closure Compiler in the Gitter!

**Comment by gkontokotsios** [comment] 2018-11-27 19:00
@steveblue: You're welcome. Yeah sure I'll let you know!
